name: Docker URI check
description: Checks URIs to Docker images in configuration files
author: Damian
inputs:
  docker-token:
    description: Token for reading the Docker registry
    required: true
runs:
  using: node16
  main: index.js
