name: Docker URI check
description: Finds and checks Docker URIs against the provided registries
author: Damian <dwood@uw.co.uk>
inputs:
  docker-registries:
    description: |
      A map of Docker registry endpoints to credentials.
      Example value:
      {
        "registry.uw.systems": {
          "username": "somebody",
          "password": "the password",
        }
      }
    required: true
  merge-base:
    description: The branch name or ref to compare against such as "master" whatever branch a PR is being merged into.
    required: true
  file-extensions:
    description: A comma separated list of file extensions that should be checked for Docker image URIs.
    required: true
runs:
  using: node16
  main: dist/index.js
