name: Docker URI check
description: Finds and checks Docker URIs against the provided registries
author: Damian <dwood@uw.co.uk>
inputs:
  docker-registries:
    description: |
      A map of Docker registry endpoints to credentials.
      Example value:
      {
        "registry.uw.systems": {
          "username": "somebody",
          "password": "the password",
        }
      }
    required: true
  working-directory:
    description: The directory to look for files
    required: false
    default: './'
  patterns:
    description: Glob patterns for files to match
    required: false
    default: '["**/*.yaml", "**/*.yml"]'
runs:
  using: node16
  main: dist/index.js
